apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::206499228565:role/eks-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-06T08:29:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1580"
  uid: 56b9da98-540d-48a6-8ffb-86c62d3ff2c0
data:
  mapUsers: |
    - userarn: arn:aws:iam::206499228565:user/workshop  
      username: admin
      groups:
        - system:masters
