apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::664966433367:role/eks-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-08T04:12:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1527"
  uid: 468192c7-7976-40bc-8f45-cfb159f227ae
data:
  mapUsers: |
    - userarn: arn:aws:iam::664966433367:user/rapa0003  
      username: admin
      groups:
        - system:masters
