apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soup-data
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kakao-shop/manifest.git
    targetRevision: HEAD
    path: ./data-mgt
  destination: 
    server: https://kubernetes.default.svc
    namespace: data-mgt
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soup-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kakao-shop/manifest.git
    targetRevision: HEAD
    path: ./ser-mgt/frontend
  destination: 
    server: https://kubernetes.default.svc
    namespace: ser-mgt
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soup-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kakao-shop/manifest.git
    targetRevision: HEAD
    path: ./ser-mgt/backend
  destination: 
    server: https://kubernetes.default.svc
    namespace: ser-mgt
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soup-ser-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kakao-shop/manifest.git
    targetRevision: HEAD
    path: ./ser-mgt/db
  destination: 
    server: https://kubernetes.default.svc
    namespace: ser-mgt
  syncPolicy:
    automated:
      selfHeal: true