apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: dbcluster
  namespace: mysql-operator
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 2
  version: 8.0.31
  router:
    instances: 2
    version: 8.0.31
  datadirVolumeClaimTemplate:
    storageClassName: mysql-efs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  mycnf: |
    [mysqld]
    default-time-zone='Asia/Seoul'
    collation-server = utf8mb4_unicode_ci
    character-set-server = utf8mb4