apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: dbcluster
  namespace: mysql-operator
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 2
  version: 8.0.31
  router:
    instances: 1
    version: 8.0.31
  datadirVolumeClaimTemplate:
    storageClassName: mysql-efs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi